name: bloc_rxdart
description: "A new Flutter project."

publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
 
  cupertino_icons: ^1.0.6
  
  get_it: ^7.7.0
   
  flutter_bloc: ^8.1.6

  
  freezed_annotation: ^2.4.1
  json_annotation: ^4.9.0

  
  dio: ^5.3.2
  retrofit: ^4.0.1

  
  rxdart:  ^0.27.7
  bloc: ^8.1.4
  go_router: ^14.2.1
  shared_preferences: ^2.3.1
  flutter_secure_storage: ^4.2.1
  encrypt: ^5.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  
  build_runner: ^2.4.6
  freezed: ^2.4.2
  json_serializable: ^6.7.1
  retrofit_generator: ^7.0.8
  mockito: ^5.4.4
  test: ^1.16.0


flutter:
  uses-material-design: true

  
  
